### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by wangwustat** [danielgribel/hg-means#1]
Thank you for the great clustering method. 
Could you add an interface in Python, such that inputs and outputs are python variables?
For example, the input data can be a numpy array, and the class labels are also a numpy array.
Could you also add some documents to explain the functions?  So that one can understand the usage better.

**Comment by vidalt** [comment]
Hello @wangwustat, thanks a lot for your interest in this project, indeed the current I/O is not really user-friendly (data passed as a file, and solution returned as a file as well). We will check what can be done to improve this aspect. Otherwise, any help (as a pull request) is also very welcome in this project.

**Comment by danielgribel** [comment]
dear @wangwustat, thank you very much for the interest in hg-means clustering. We updated the Python package to support arrays representing the dataset and labels. If you already have hg-means installed, you need to uninstall and then install it via pip. Once installed, all you need is to import the package and pass a list of lists for the dataset, and a list for the labels. The Readme file in this repository is updated, and you can find examples of how to run it. Please let us know if you managed to execute it, and if any other improvements could be made. We also invite you to contribute with any other additional feature.

**Comment by wangwustat** [comment]
Thanks a lot for your work and reply. I think my request is fully resolved.
